### ISSUE TITLE
How to use darwin_nfs_sys_prot as the argument data in func unix.Mount

### ISSUE THREAD

**Issue by ikmak** [buildbarn/go-xdr#1]
Hello, I want to implement mount a NFS in macOS by using Golang.
I've seen the commit https://go-review.googlesource.com/c/sys/+/405494?tab=comments
I don't know how to pass the last argument "data" of func unix.Mount
e.g. The command line
```bash  
mount -o port=portnumber,mountport=portnumber -t nfs "hostname:/sharefolder" "/Volumes/mountpoint"
```
How to mount the NFS by using Golang same as the mount command line above. 
Could you write a simple example code for me plz, thank you!

**Comment by EdSchouten** [comment]
Hey! You can find an example here:

https://github.com/buildbarn/bb-remote-execution/blob/master/pkg/filesystem/virtual/configuration/nfsv4_mount_darwin.go

That said, keep in mind that darwin_nfs_sys_prot is, as far as I know, not a stable API. If you can get away with just calling `mount_nfs`, you should. Using darwin_nfs_sys_prot is mainly of interest if you want to set options that are not exposed through the `mount_nfs` utility.
